### ISSUE TITLE
Build script doesn’t test on COOP report

### ISSUE THREAD

**Issue by sagelga** [DobaKung/IT-KMITL-Latex#22]
The script only tests on project report. 

Ways to fix:
- add the coop report test that is **independent** to project report

**Comment by sagelga** [comment]
I can’t tag @kavinvin but I can tag @DobaKung

**Comment by kavinvin** [comment]
Let's settle with thesis thing first. This can be solved later in the main repo.

**Comment by sagelga** [comment]
This issue is so stale @DobaKung

**Comment by kavinvin** [comment]
Can we merge it first? The pull request is already big enough. And coop folder is kind of independent from the project one. The one who's still using this can solve it too if they want.

**Comment by sagelga** [comment]
How much efforts you need to fix the issue? I still don’t understand what’s keeping this PR on hold.

And for the “should we merge”, i felt like we should merge on things that works fine, and open another PR on things that are broken.

**Comment by kavinvin** [comment]
@sagelga I guess it will requires not too much effort if I don't need to fix the error things when adding test to COOP. And it does have errors in the COOP file itself. Maybe because our build process is different? I'll try to fix it soon.

**Comment by sagelga** [comment]
Almost all of the Coop work is inherited by P’ Chin. You might need his help tho. Else you can figured this out, that’ll be great.

**Comment by kavinvin** [comment]
@sagelga I fixed the error. Only need to add Angsana New fonts.

But, "Coop" uses Angsana and "Project" uses Kinnari. Should we change them to be the same? I guess we have to uses Angsana anyway when submitting the real report. Any thoughts? @DobaKung

**Comment by sagelga** [comment]
I remembered that Kinnari is for replacing “missing fonts” in OS that is not Windows. I still don’t know that they are ok with Kinnari or not, but I felt like it’s a yes because Doba use it as a “resemblance” of Angsana New and no one will noticed it.


Could you make it to use Kinnari as an **fallback font** for non-Windows? @kavinvin

**Comment by kavinvin** [comment]
@sagelga I think Angsana New is also fine for non-Windows? (If we ignore the copyright thing)

And I don't think they looks similar. It looks very different in bold title. If I remember it correctly, @DobaKung still needs to change his to Angsana when submitting the final file.

**Comment by zartre** [comment]
Yes, I switched to Angsana in the final file because Kinnari's bold weight is not bold enough. Will update the class to use Angsana New.

**Comment by sagelga** [comment]
Aaaa. Generic Doba thing.

**Comment by sagelga** [comment]
I guess this issue is also related to #2.

Remind someone to also close #2 when this issue is fixed.

**Comment by sagelga** [comment]
Should we just merge this repo to DSMLR and continue opening the PR?
Hoping other ppl send commit and fix this things up. 

If it still in this repo, no one will knows this fork existed and did not get any benefits by our work

**Comment by sagelga** [comment]
This issue is fixed with #25
